"""
flask_server_secure.py
----------------------
This is the SECURE version of the Flask data receiver server.

It listens on HTTPS (port 5443) WITH TLS encryption using a
self-signed X.509 certificate and RSA 4096-bit private key.

This means all PLC data transmitted to this server is encrypted
and cannot be read by anyone intercepting the network traffic.

Purpose in this project:
    Demonstrate the secure communication scenario where PKI and TLS
    protect the industrial data pipeline. This represents the
    "after security" scenario.

Endpoints:
    POST /plc-data  - Receive encrypted PLC sensor data
    GET  /data      - View all received data records
"""

import datetime
from flask import Flask, jsonify, request

# ─── Application Setup ────────────────────────────────────────────────────────

app = Flask(__name__)

# In-memory storage for all received PLC data records
received_data = []

# TLS certificate and private key paths (generated by generate_cert.py)
CERT_FILE = "cert.pem"
KEY_FILE = "key.pem"

# ─── Routes ───────────────────────────────────────────────────────────────────


@app.route("/plc-data", methods=["POST"])
def receive_data():
    """
    Receive PLC sensor data sent by the secure bridge script.

    SECURITY NOTE:
        This endpoint uses HTTPS/TLS. The JSON payload is fully
        encrypted during transmission. Wireshark will only show
        encrypted binary data - the actual values are unreadable
        without the private key.
    """
    # Parse the incoming JSON body (decrypted automatically by TLS)
    data = request.get_json()

    # Attach a server-side timestamp
    data["timestamp"] = str(datetime.datetime.now())

    # Store the record in memory
    received_data.append(data)

    # Print summary to console
    print(f"\n[SECURE - HTTPS] Received PLC Data:")
    print(f"   Timestamp   : {data['timestamp']}")
    print(f"   Temperature : {data.get('temperature')} C")
    print(f"   Heater ON   : {data.get('heater_on')}")
    print(f"   Alarm High  : {data.get('alarm_high')}")
    print(f"   System OK   : {data.get('system_ok')}")
    print(f"   PLC Status  : {data.get('plc_status')}")

    return jsonify(
        {
            "status": "received",
            "timestamp": data["timestamp"],
            "encryption": "TLS 1.2/1.3 - AES encrypted in transit",
        }
    )


@app.route("/data", methods=["GET"])
def show_data():
    """
    Return all received PLC data records.
    """
    return jsonify({"total_records": len(received_data), "records": received_data})


# ─── Entry Point ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 55)
    print("  Flask PLC Data Receiver - SECURE (HTTPS) MODE")
    print("=" * 55)
    print("  Protocol  : HTTPS (TLS encrypted)")
    print("  Port      : 5443")
    print("  Cert      : cert.pem (RSA 4096-bit, SHA-256)")
    print("  Key       : key.pem")
    print("  Endpoint  : https://127.0.0.1:5443/plc-data")
    print("=" * 55)

    # Run with TLS using the generated certificate and private key
    app.run(
        host="0.0.0.0",
        port=5443,
        ssl_context=(CERT_FILE, KEY_FILE),  # Enable TLS
        debug=False,
    )
