"""
fix_and_upload.py
-----------------
This script prepares and uploads a compiled PLC program to the OpenPLC Runtime.

Problem it solves:
    The OpenPLC Editor generates source files for Arduino targets, but the
    OpenPLC Runtime (Linux/MSYS2) needs slightly different files to compile.
    Specifically:
    - Res0.c must include POUS.inc to get MAIN_init__ and MAIN_body__ functions
    - c_blocks_code.cpp must exist (even empty) for the build script to succeed

Workflow:
    1. Read the original Res0.c and append #include "POUS.inc"
    2. Create an empty c_blocks_code.cpp stub file
    3. Package all source files into a ZIP archive
    4. Authenticate with OpenPLC Runtime API
    5. Upload the ZIP for compilation and deployment
"""

import os
import zipfile

import requests
import urllib3

# Suppress SSL warnings caused by the self-signed certificate on OpenPLC Runtime
urllib3.disable_warnings()

# ─── Configuration ────────────────────────────────────────────────────────────

# OpenPLC Runtime HTTPS API endpoint
BASE_URL = "https://127.0.0.1:8443"

# Directory containing the generated C source files from OpenPLC Editor
SRC_DIR = r"E:\Parastoo\STU\Uni\Msc\2\Internet Security\Project\with OPENPLC - C\PLC\build\OpenPLC Simulator\src"

# Output ZIP archive path (will be uploaded to the Runtime)
ZIP_PATH = r"E:\Parastoo\STU\Uni\Msc\2\Internet Security\Project\with OPENPLC - C\PLC\plc_src.zip"

# Temporary fixed version of Res0.c (with POUS.inc appended)
RES0_FIXED_PATH = r"E:\Parastoo\STU\Uni\Msc\2\Internet Security\Project\with OPENPLC - C\PLC\Res0_fixed.c"

# Stub file: the build script requires this file to exist even if empty
EMPTY_CPP_PATH = r"E:\Parastoo\STU\Uni\Msc\2\Internet Security\Project\with OPENPLC - C\PLC\c_blocks_code.cpp"

# ─── Step 1: Fix Res0.c ───────────────────────────────────────────────────────

# Read the original Res0.c generated by OpenPLC Editor
res0_original = open(os.path.join(SRC_DIR, "Res0.c")).read()

# Append the include directive so that MAIN_init__ and MAIN_body__ are compiled.
# Without this, the linker fails with "undefined reference to MAIN_init__".
res0_fixed = res0_original + '\n#include "POUS.inc"\n'

# Write the fixed version to a temporary file
with open(RES0_FIXED_PATH, "w") as f:
    f.write(res0_fixed)

print("[1/4] Res0.c patched with POUS.inc include.")

# ─── Step 2: Create empty c_blocks_code.cpp ──────────────────────────────────

# The OpenPLC Runtime build script (compile.sh) always tries to compile
# c_blocks_code.cpp. If it does not exist, the build fails immediately.
# We create an empty stub so the build can proceed.
with open(EMPTY_CPP_PATH, "w") as f:
    f.write("// Empty stub - no custom C function blocks used in this project\n")

print("[2/4] Empty c_blocks_code.cpp stub created.")

# ─── Step 3: Build the ZIP archive ───────────────────────────────────────────

with zipfile.ZipFile(ZIP_PATH, "w", zipfile.ZIP_DEFLATED) as zf:

    for item in os.listdir(SRC_DIR):
        # Skip the original Res0.c — we use the patched version instead
        if item == "Res0.c":
            continue

        item_path = os.path.join(SRC_DIR, item)

        if os.path.isfile(item_path):
            # Add regular files directly to the ZIP root
            zf.write(item_path, item)

        elif os.path.isdir(item_path):
            # Add subdirectory contents (e.g. the lib/ folder with IEC headers)
            for f2 in os.listdir(item_path):
                zf.write(os.path.join(item_path, f2), os.path.join(item, f2))

    # Add the patched Res0.c (replaces the original in the archive)
    zf.write(RES0_FIXED_PATH, "Res0.c")

    # Add the empty C++ stub
    zf.write(EMPTY_CPP_PATH, "c_blocks_code.cpp")

print(f"[3/4] ZIP archive created: {ZIP_PATH}")

# ─── Step 4: Upload to OpenPLC Runtime ───────────────────────────────────────

# Authenticate with the OpenPLC Runtime REST API to get a JWT access token
login_response = requests.post(
    f"{BASE_URL}/api/login",
    json={"username": "admin", "password": "admin123"},
    verify=False,  # Accept self-signed TLS certificate
)
token = login_response.json().get("access_token")
auth_headers = {"Authorization": f"Bearer {token}"}

print("[4/4] Authenticated with OpenPLC Runtime. Uploading ZIP...")

# Upload the ZIP file for compilation and deployment
with open(ZIP_PATH, "rb") as f:
    upload_response = requests.post(
        f"{BASE_URL}/api/upload-file",
        headers=auth_headers,
        files={"file": ("plc_src.zip", f, "application/zip")},
        verify=False,
    )

result = upload_response.json()
print(f"Upload result: {result}")

# CompilationStatus: COMPILING means the Runtime accepted the file and started building
if result.get("UploadFileFail") == "":
    print("✅ Upload successful! PLC program is now compiling on the Runtime.")
else:
    print(f"❌ Upload failed: {result.get('UploadFileFail')}")
